all: Address1 Ptr1 Ptr2 Array2 Array3 Array3b \
    Address2 Ptr3 StrLen1 StrLen2 StrLen3 \
    Const1b Array2b Null1b Null1

Address1: Address1.cpp
	g++ -o $@ $<

Ptr1: Ptr1.cpp
	g++ -o $@ $<

Ptr2: Ptr2.cpp
	g++ -o $@ $<

Array2: Array2.cpp
	g++ -o $@ $<

Array3: Array3.cpp
	g++ -o $@ $<

Array3b: Array3b.cpp
	g++ -o $@ $<

Address2: Address2.cpp
	g++ -o $@ $<

Ptr3: Ptr3.cpp
	g++ -o $@ $<

StrLen1: StrLen1.cpp
	g++ -o $@ $<

StrLen2: StrLen2.cpp
	g++ -o $@ $<

StrLen3: StrLen3.cpp
	g++ -o $@ $<

Const1b: Const1b.cpp
	g++ -o $@ $<

#Const1: Const1.cpp
#	g++ -o $@ $<

Array2b: Array2b.cpp
	g++ -o $@ $<

Null1b: Null1b.cpp
	g++ -o $@ $<

Null1: Null1.cpp
	g++ -o $@ $<
