all: Ref1b Ref1 String1 String1b String2 Proto1 \
   Include1 Rand1 Rand1b Rand1c Math1 NumericalError1 \
   NumericalError1b Overload1 Bool1 Bool2


Ref1b: Ref1b.cpp
	g++ -o $@ $<

Ref1: Ref1.cpp
	g++ -o $@ $<

String1: String1.cpp
	g++ -o $@ $<

String1b: String1b.cpp
	g++ -o $@ $<

String2: String2.cpp
	g++ -o $@ $<

Proto1: Proto1.cpp
	g++ -o $@ $<

Include1: Include1.cpp Include1.h
	g++ -o $@ $<

Rand1: Rand1.cpp
	g++ -o $@ $<

Rand1b: Rand1b.cpp
	g++ -o $@ $<

Rand1c: Rand1c.cpp
	g++ -o $@ $<

Math1: Math1.cpp
	g++ -o $@ $<

NumericalError1: NumericalError1.cpp
	g++ -o $@ $<

NumericalError1b: NumericalError1b.cpp
	g++ -o $@ $<

Overload1: Overload1.cpp
	g++ -o $@ $<

Bool1: Bool1.cpp
	g++ -o $@ $<

Bool2: Bool2.cpp
	g++ -o $@ $<

######################################################################
