
all: Variable1 Variable2 Variable4 Input1 If1 If2 \
      If3 For1 Array1 For2 For3 While1 While1c Break1

Variable1: Variable1.cpp
	g++ -o $@ $<

Variable2: Variable2.cpp
	g++ -o $@ $<

Variable4: Variable4.cpp
	g++ -o $@ $<

Input1: Input1.cpp
	g++ -o $@ $<

If1: If1.cpp
	g++ -o $@ $<

If2: If2.cpp
	g++ -o $@ $<

If3: If3.cpp
	g++ -o $@ $<

For1: For1.cpp
	g++ -o $@ $<

Array1: Array1.cpp
	g++ -o $@ $<

For2: For2.cpp
	g++ -o $@ $<

For3: For3.cpp
	g++ -o $@ $<

While1: While1.cpp
	g++ -o $@ $<

While1c: While1c.cpp
	g++ -o $@ $<

Break1: Break1.cpp
	g++ -o $@ $<
##########################################################
# endline
